version: '3.7'
services:
  api:
    build: .
    tty: true
    volumes:
      - ./api:/app
      - /app/node_modules
    depends_on:
      - db
    ports:
      - '3000:3000'
      - '5555:5555'
        
  db:
    container_name: db
    image: postgres:14.5-bullseye
    platform: linux/amd64
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - TZ=${TZ}
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - '5432:5432'