swagger: "3.0"
info:
  version: "1.0"
  title: CODE_DUEL API
  description: CODE_DUELのAPI仕様書です。
  contact:
    name: CODE_DUEL
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /signUp:
    post:
      tags:
        - user
      summary: ユーザー登録
      description: ユーザーの登録を行う。初回アクセス時のみフロントからリクエストが送られる。
      operationId: signUp
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              user_id:
                type: number
  /signIn:
    post:
      tags:
        - user
      summary: ユーザーログイン
      description: ログインを行う。ブラウザにidが保存されている場合にリクエストが送られる。
      operationId: signIn
      requestBody:
        content: application/json
        schema:
          type: object
          properties:
            user_id:
              type: number
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              user_id:
                type: number

  /deck:
    get:
      tags:
        - decks
      summary: デッキ一覧を取得する
      description: デッキ一覧を取得する
      operationId: getDecks
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: "#/definitions/Deck"
  /draw:
    get:
      tags:
        - cards
      summary: カードを引く
      description: 必要な枚数だけカードを引く
      operationId: drawCard
      parameters:
        - name: deck_id
          in: query
          description: デッキのID
          required: true
          type: number
        - name: card_count
          in: query
          description: 必要なカードの枚数
          required: true
          type: number
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: "#/definitions/card"
  /cards:
    get:
      tags:
        - cards
      summary: カード一覧を取得する
      description: カード一覧を取得する
      operationId: getCards
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/cards"
  /cards/{id}:
    get:
      tags:
        - cards
      summary: カードを取得する
      description: カードを取得する
      operationId: getCard
      parameters:
        - name: id
          in: path
          description: カードのID
          required: true
          type: number
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/card"
  /combo:
    get:
      tags:
        - combos
      summary: コンボを取得する
      description: コンボを取得する
      operationId: getCombo
      parameters:
        - name: cards
          in: query
          description: カードのID
          required: true
          type: array
          items:
            type: number
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/combo"

definitions:
  Deck:
    title: Deck
    type: object
    properties:
      name:
        type: string
      cards:
        type: array
        items:
          $ref: "#/definitions/card"
  card:
    title: card
    type: object
    properties:
      name:
        type: string
      value:
        type: integer
      type:
        type: string
        enum: [attack, heal, absorption]
  cards:
    title: cards
    type: array
    items:
      $ref: "#/definitions/card"
  combo:
    title: combo
    type: object
    properties:
      name:
        type: string
      cards:
        type: array
        items:
          $ref: "#/definitions/card"
      type:
        type: string
        enum: [attack, heal, absorption]
      value:
        type: integer

tags:
  - name: user
  - name: cards
  - name: decks
  - name: combos
responses: {}
